
import { Language } from './types.ts';

export const UI_TEXT = {
  en: {
    title: "Intelligent Stock Agent",
    searchPlaceholder: "Enter company, ticker, or concept (e.g., 'Apple', 'AAPL', 'electric vehicles')",
    searchButton: "Analyze",
    languageToggle: "中文",
    reset: "New Analysis",
    findingCompanies: "Identifying relevant companies...",
    analyzingCompany: "Analyzing {companyName}...",
    generatingQuestions: "Generating research questions...",
    answeringQuestions: "Answering questions ({current}/{total})...",
    synthesizingReport: "Synthesizing investment thesis...",
    generatingFinalConclusion: "Formulating final conclusion...",
    analysisComplete: "Analysis Complete",
    focusCompany: "Focus Company",
    candidateCompany: "Candidate Company",
    companyProfile: "Company Profile",
    ticker: "Ticker",
    exchange: "Exchange",
    currentPrice: "Current Price",
    dayChangePct: "Day Change",
    high52w: "52-Week High",
    low52w: "52-Week Low",
    profitLoss: "Loss-making",
    peTtm: "PE (TTM)",
    weekChange: "1-Week Change",
    monthChange: "1-Month Change",
    investmentThesis: "Investment Thesis",
    finalConclusion: "Final Investment Conclusion",
    detailedAnalysis: "Detailed Analysis (Q&A)",
    sources: "Sources",
    followUp: "Suggested Follow-up Questions",
    askFollowUp: "Ask Selected",
    errorTitle: "An Error Occurred",
    interrupted: "Analysis Interrupted",
    interruptedMessage: "The previous analysis was interrupted. You can review the progress made or start a new analysis.",
    history: "History",
    clearHistory: "Clear All History",
    loadReport: "Load Report",
    deleteReport: "Delete Report",
    reportGeneratedAt: "Report generated at",
    freshnessAuditTitle: "Data Freshness Audit",
    freshnessLatestPeriod: "Latest period found",
    freshnessRecentCoverage: "Recent (last 3 months) coverage",
    freshnessLatestQuarter: "Includes latest disclosed quarter evidence",
    freshnessLatestAnnual: "Includes latest complete annual report evidence",
    freshnessFallbackCount: "Answers relying on old data fallback",
    emptyHistory: "No reports found. Complete an analysis to see it here.",
    savingReport: "Saving report to history...",
    saveSuccess: "Report saved to history successfully.",
    saveFailed: "Report could not be saved to history",
    conclusion: {
      UpstreamSupplyChain: "Upstream/Supply Chain",
      MarketPosition: "Market Position",
      BusinessModel: "Business Model",
      Financials: "Financials",
      OutlookRisks: "Outlook & Risks",
      summary: "Summary",
      evidence: "Evidence"
    }
  },
  cn: {
    title: "智能股票投研助手",
    searchPlaceholder: "输入公司、代码或概念（如 '苹果', 'AAPL', '新能源汽车'）",
    searchButton: "开始分析",
    languageToggle: "English",
    reset: "开始新分析",
    findingCompanies: "正在识别相关公司...",
    analyzingCompany: "正在分析 {companyName}...",
    generatingQuestions: "正在生成研究问题...",
    answeringQuestions: "正在回答问题 ({current}/{total})...",
    synthesizingReport: "正在生成投资报告...",
    generatingFinalConclusion: "正在形成最终结论...",
    analysisComplete: "分析完成",
    focusCompany: "核心公司",
    candidateCompany: "候选公司",
    companyProfile: "公司简介",
    ticker: "股票代码",
    exchange: "交易所",
    currentPrice: "当前股价",
    dayChangePct: "日涨幅",
    high52w: "52周最高",
    low52w: "52周最低",
    profitLoss: "亏损",
    peTtm: "市盈率(PE)",
    weekChange: "周涨幅",
    monthChange: "月涨幅",
    investmentThesis: "投资论点",
    finalConclusion: "最终投资结论",
    detailedAnalysis: "详细分析 (问答)",
    sources: "信息来源",
    followUp: "建议追问",
    askFollowUp: "提问选中项",
    errorTitle: "发生错误",
    interrupted: "分析已中断",
    interruptedMessage: "上次分析已中断。您可以查看已有进度或开始新的分析。",
    history: "历史记录",
    clearHistory: "清空历史记录",
    loadReport: "加载报告",
    deleteReport: "删除报告",
    reportGeneratedAt: "报告生成时间",
    freshnessAuditTitle: "时效性审计",
    freshnessLatestPeriod: "检测到的最新周期",
    freshnessRecentCoverage: "最近三个月覆盖率",
    freshnessLatestQuarter: "是否包含最新已披露季度证据",
    freshnessLatestAnnual: "是否包含最新完整年报证据",
    freshnessFallbackCount: "回退到旧数据的回答数",
    emptyHistory: "暂无报告。完成一次分析后将在此处显示。",
    savingReport: "正在保存报告到历史记录...",
    saveSuccess: "报告已成功保存到历史记录。",
    saveFailed: "报告未能保存到历史记录",
    conclusion: {
      UpstreamSupplyChain: "上游/供应链",
      MarketPosition: "市场地位",
      BusinessModel: "商业模式",
      Financials: "财务状况",
      OutlookRisks: "前景与风险",
      summary: "总结",
      evidence: "证据"
    }
  }
};

export const getUIText = (lang: Language) => UI_TEXT[lang];
