
import { Language } from './types.ts';

/** Primary product branding (tradealpha.cc). */
export const BRAND = {
  name: 'Trade Alpha',
  documentTitle: 'Trade Alpha',
  productNameEn: 'Intelligent Stock Agent',
  productNameCn: '智能股票投研助手',
  domain: 'tradealpha.cc',
} as const;

/** Set to true to show Batch Queue tab and related UI (backend routes remain available). */
export const FEATURE_BATCH_QUEUE = true;

export const UI_TEXT = {
  en: {
    brandName: BRAND.name,
    productSubtitle: BRAND.productNameEn,
    title: BRAND.name,
    searchPlaceholder: "Enter company name or stock ticker",
    searchButton: "Start Analysis",
    startingSearch: "Starting...",
    searchSubtitle: "AI-powered insights for US, Hong Kong, and A-share markets.",
    languageToggle: "中文",
    viewSingle: "Single",
    viewBatch: "Batch Analysis",
    batchTitle: "Batch Analysis",
    batchSubtitle: "Submit multiple tickers for background processing. Close the browser and check back anytime.",
    batchAddTickersTitle: "Add tickers to queue",
    batchTickersPlaceholder: "Enter tickers separated by commas or new lines\ne.g. AAPL, MSFT, HK.00700",
    batchStartButton: "Start Batch",
    batchSubmitting: "Submitting...",
    batchDashboardTitle: "Queue dashboard",
    batchRefresh: "Refresh",
    batchStatPending: "Pending",
    batchStatProcessing: "Processing",
    batchStatCompleted: "Completed",
    batchStatFailed: "Failed",
    batchJobPending: "Pending",
    batchJobProcessing: "Processing",
    batchJobCompleted: "Completed",
    batchJobFailed: "Failed",
    batchEmptyState: "No jobs in queue. Add tickers above to start batch analysis.",
    batchAutoRefreshHint: "Auto-refreshes every 15 seconds · queue list persists when you switch tabs",
    batchNoTickersError: "Please enter at least one ticker",
    batchInvalidTickersError: "No valid tickers found",
    batchColTicker: "Ticker",
    batchColCompany: "Company",
    batchColPrice: "Price",
    batchColConclusion: "Conclusion",
    batchColStatus: "Status & progress",
    batchColActions: "Actions",
    batchCreated: "Created",
    batchViewReport: "View report",
    batchLoadingReport: "Loading...",
    batchRetry: "Retry",
    batchResume: "Resume",
    batchRetrying: "Retrying...",
    batchLoadReportError: "Failed to load report",
    batchEmptyReport: "Report payload is empty",
    batchConclusionUnclassified: "Unclassified",
    batchConclusionStrongBuy: "Strong Buy",
    batchConclusionBuy: "Buy",
    batchConclusionStrongSell: "Strong Sell",
    batchConclusionSell: "Sell",
    batchConclusionHold: "Hold",
    batchJobStatusTitle: "Batch job in progress",
    batchJobStatusSubtitle: "Your tickers are running in the background. Track progress here or open the full queue anytime.",
    batchStatTotal: "Total",
    batchJobProgressLabel: "{done} of {total} finished",
    batchJobPollingHint: "Updating automatically — leave this page anytime and check the full queue later.",
    batchJobViewQueue: "View full queue",
    batchJobCloseStatus: "Dismiss",
    reset: "New Analysis",
    findingCompanies: "Identifying relevant companies...",
    analyzingCompany: "Analyzing {companyName}...",
    generatingQuestions: "Generating research questions...",
    answeringQuestions: "Completed {current}/{total} questions...",
    synthesizingReport: "Synthesizing investment thesis...",
    generatingFinalConclusion: "Formulating final conclusion...",
    analysisComplete: "Analysis Complete",
    focusAnalysisSaved: "Focus company analysis complete — report saved.",
    savingFocusReport: "Saving focus company report...",
    focusReportSaved: "Focus company report saved. Start candidate analysis from each tab when ready.",
    startCandidateAnalysis: "Start Analysis",
    startCandidateAnalysisHint: "Deep analysis (questions, Q&A, thesis) runs only after you click. Saves tokens.",
    candidateAnalyzing: "Analyzing candidate...",
    stepTimelineToggle: "Step timing",
    stepTimelineTitle: "Analysis step timeline",
    focusCompany: "Focus Company",
    candidateCompany: "Candidate Company",
    companyProfile: "Company Profile",
    companyQuickTake: "At a Glance",
    ticker: "Ticker",
    exchange: "Exchange",
    currentPrice: "Current Price",
    dayChangePct: "Day Change",
    high52w: "52-Week High",
    low52w: "52-Week Low",
    profitLoss: "Loss-making",
    peTtm: "PE (TTM)",
    marketCap: "Market Cap",
    floatMarketCap: "Float Market Cap",
    weekChange: "1-Week Change",
    monthChange: "1-Month Change",
    investmentThesis: "Investment Thesis",
    investmentNarrative: "Investment Narrative",
    crossDimensionalInsights: "Cross-Dimensional Insights",
    finalConclusion: "Final Investment Conclusion",
    detailedAnalysis: "Detailed Analysis (Q&A)",
    sources: "Sources",
    followUp: "Suggested Follow-up Questions",
    askFollowUp: "Ask Selected",
    errorTitle: "An Error Occurred",
    interrupted: "Analysis Interrupted",
    interruptedMessage: "The previous analysis was interrupted. You can review the progress made or start a new analysis.",
    history: "History",
    historyReportsTab: "Analysis Reports",
    historyComparisonsTab: "Compare History",
    compareOpenResult: "Open results",
    compareNewCompare: "New comparison",
    compareLoadingSessions: "Loading comparisons...",
    compareSessionRunCount: "{count} runs",
    compareSidebarHint: "Saved rankings and scores — reopen anytime.",
    compareHistoryInSidebar: "Saved comparisons live in the sidebar → Compare History tab.",
    clearHistory: "Clear All History",
    loadReport: "Load Report",
    deleteReport: "Delete Report",
    reportGeneratedAt: "Report generated at",
    freshnessAuditTitle: "Data Freshness Audit",
    freshnessLatestPeriod: "Latest period found",
    freshnessRecentCoverage: "Recent (last 3 months) coverage",
    freshnessLatestQuarter: "Includes latest disclosed quarter evidence",
    freshnessLatestAnnual: "Includes latest complete annual report evidence",
    freshnessFallbackCount: "Answers relying on old data fallback",
    emptyHistory: "No reports found. Complete an analysis to see it here.",
    savingReport: "Saving report to history...",
    progressReportSaved: "Report updated with latest analysis progress.",
    saveSuccess: "Report saved to history successfully.",
    saveFailed: "Report could not be saved to history",
    followUpAnalysis: "Follow-up Analysis",
    followUpAll: "Follow-up All",
    followUpCompany: "Follow-up This Company",
    followUpConfirmTitle: "Start Follow-up Analysis",
    followUpConfirmDesc: "Focus on changes since the prior report. Baseline company facts will be reused; research targets events and thesis updates in the intervening period.",
    followUpPriorReport: "Baseline report",
    followUpPriorConclusion: "Prior conclusion",
    followUpPriorPrice: "Prior price",
    followUpCurrentPrice: "Current price",
    followUpDaysSince: "Days since prior",
    followUpTargetCompanies: "Companies to follow up",
    followUpStart: "Start Follow-up",
    followUpCancel: "Cancel",
    followUpBannerTitle: "Follow-up Analysis",
    followUpVsPrior: "vs Prior Analysis",
    followUpRatingUpgrade: "Rating upgraded",
    followUpRatingMaintain: "Rating maintained",
    followUpRatingDowngrade: "Rating downgraded",
    followUpPriceChange: "Price change",
    followUpNoEligible: "No complete reports available for follow-up.",
    followUpLoadingPrices: "Refreshing market data...",
    followUpGeneratingQuestions: "Generating follow-up questions...",
    followUpViewPriorReport: "View baseline report",
    viewInitialReport: "View Initial Report",
    compareVsPrevious: "vs Last",
    compareVsInitial: "vs Initial",
    compareOpenReport: "Open full report →",
    compareTitle: "Cross-Company Compare",
    compareSubtitle: "Pick 2–5 analyzed companies (focus or candidate), rank by conviction, upside, downside protection, and market theme fit.",
    compareBasketTab: "Basket",
    compareHistoryTab: "Compare History",
    compareSelected: "Selected for compare",
    compareClearBasket: "Clear basket",
    compareStart: "Run comparison",
    compareRunning: "Comparing…",
    comparePickFromHistory: "Pick companies from saved reports",
    compareNoHistory: "No saved reports yet. Run an analysis first.",
    compareNoEligible: "No fully analyzed companies in this report.",
    compareResultsTitle: "Comparison Results",
    compareRunAt: "Compared at",
    compareFollowUp: "Follow-up compare",
    compareFollowUpRefreshReports: "Follow-up (refresh to latest reports)",
    compareChangeSummary: "Changes vs prior run",
    compareHotTopics: "Market hot topics (D4)",
    compareHotTopicsAt: "Hot topics fetched at",
    compareMatchedThemes: "Matched themes",
    comparePortfolioSummary: "Portfolio summary",
    compareBackToBasket: "Back to basket",
    compareNoSessions: "No saved comparisons yet.",
    compareSearchPlaceholder: "Search company or ticker…",
    compareSearchNoResults: "No matching comparisons",
    compareUntitledSession: "Untitled comparison",
    compareViewLatest: "View latest",
    viewCompare: "Compare",
    compareSavedToDb: "Saved to database",
    compareSessionId: "Session ID",
    compareRunId: "Run ID",
    compareSavedHint: "Find this comparison anytime under Compare History.",
    compareProgressTitle: "Comparison in progress",
    compareProgressSubtitle: "Stay on this page or switch tabs — comparison continues in the background.",
    compareStepLoadingReports: "Load analysis reports",
    compareStepBuildingDigests: "Build comparison summaries",
    compareStepFetchingTopics: "Fetch market hot topics",
    compareStepAiRanking: "AI ranking & scoring",
    compareStepSaving: "Save results",
    compareProgressHint: "Usually takes 1–3 minutes for 5 companies. AI ranking is the slowest step.",
    compareProgressFailed: "Comparison failed",
    compareProgressPercent: "{percent}% complete",
    compareProgressCompanies: "Companies in this comparison",
    loginWithGoogle: "Continue with Google",
    loginSigningIn: "Signing in...",
    loginTabSignIn: "Sign in",
    loginTabSignUp: "Sign up",
    loginEmailLabel: "Email",
    loginPasswordLabel: "Password",
    loginConfirmPasswordLabel: "Confirm password",
    loginCodeLabel: "Verification code",
    loginSendCode: "Send code",
    loginResendCode: "Resend code",
    loginResendIn: "Resend in {seconds}s",
    loginCompleteSignUp: "Complete registration",
    loginSignInWithEmail: "Sign in with email",
    loginOrContinueWith: "Or continue with",
    loginCodeSentTo: "Code sent to {email}",
    loginCodeDevHint: "SMTP is not configured — check the dev server terminal for your 6-digit code.",
    loginPasswordHint: "At least 8 characters",
    loginInvalidEmail: "Enter a valid email address",
    loginNotConfigured: "Supabase auth is not configured. On Cloud Run set SUPABASE_URL and NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY (runtime). For local dev use VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in .env.",
    usageTierFree: "Free: {remaining} of {limit} analyses left",
    usageTierLocked: "Free access ended — subscription required",
    usageTierPaid: "Pro: unlimited analyses",
    usageFreeEnds: "Free window ends {date}",
    usageRemaining: "{remaining} of {limit} remaining",
    usageTrialEnds: "Free window ends {date}",
    usageLimitReached: "Subscribe to continue: $3.8 for 7 days unlimited, then $19.8/month.",
    upgrade: "Subscribe",
    memberProBadge: "Pro",
    subscriptionActiveTitle: "Pro member",
    subscriptionActiveSubtitle: "Unlimited analyses",
    subscriptionNextBilling: "Next billing: {date}",
    subscriptionManageHint: "Manage or cancel in your PayPal account",
    subscriptionTitle: "Subscribe to Pro",
    subscriptionSubtitle: "$3.8 for your first 7 days (unlimited analyses). Then $19.8/month — billed automatically by PayPal.",
    subscriptionBenefits: [
      "Unlimited company analyses every day",
      "7-day intro access for $3.8",
      "Auto-renews at $19.8/month after 7 days (cancel anytime in PayPal)",
      "Save reports, compare companies, and track returns",
    ],
    subscriptionFootnote: "Secure recurring payment via PayPal. Cancel anytime in your PayPal account.",
    signOut: "Sign out",
    returnTrackingTitle: "Return tracking (buy at baseline)",
    returnTrackingHint: "Assumes purchase at the latest price on the baseline date. Each day you reopen adds one timeline point.",
    returnTrackingAnchorPrice: "Baseline price",
    returnTrackingCurrentPrice: "Latest price",
    returnTrackingReturn: "Return since baseline",
    returnTrackingTimeline: "Return timeline",
    comparisonModeLabel: "Compare",
    companyTimeline: "Analysis Timeline",
    historyGroupedByTicker: "By Company",
    historyFlatList: "All Reports",
    timelineReports: "reports",
    viewThisReport: "Open",
    currentReportMarker: "Current",
    compareBaselineDate: "Baseline date",
    historyLoadError: "Could not load history",
    historyRetry: "Retry",
    historyReportCount: "{loaded} / {total} reports",
    historyLoadingMore: "Loading more reports…",
    historyEmptyAfterError: "Reports may still exist on the server. Retry or restart the backend.",
    historySearchPlaceholder: "Search company or ticker…",
    historySearchNoResults: "No matching reports",
    conclusion: {
      UpstreamSupplyChain: "Upstream/Supply Chain",
      MarketPosition: "Market Position",
      BusinessModel: "Business Model",
      Financials: "Financials",
      OutlookRisks: "Outlook & Risks",
      MarketSentiment: "Market Sentiment",
      IndustryCycle: "Industry Cycle",
      ExpectationGap: "Market Expectation Gap",
      summary: "Summary",
      evidence: "Evidence"
    }
  },
  cn: {
    brandName: BRAND.name,
    productSubtitle: BRAND.productNameCn,
    title: BRAND.name,
    searchPlaceholder: "输入公司或者股票代码",
    searchButton: "开始分析",
    startingSearch: "正在启动...",
    searchSubtitle: "覆盖美股、港股与 A 股的 AI 投研助手",
    languageToggle: "English",
    viewSingle: "单次分析",
    viewBatch: "批量分析",
    batchTitle: "批量分析",
    batchSubtitle: "一次提交多只股票，后台自动分析。可随时关闭页面，稍后再回来查看。",
    batchAddTickersTitle: "添加股票到队列",
    batchTickersPlaceholder: "输入股票代码，用逗号或换行分隔\n例如：AAPL, MSFT, HK.00700",
    batchStartButton: "开始批量分析",
    batchSubmitting: "提交中...",
    batchDashboardTitle: "队列看板",
    batchRefresh: "刷新",
    batchStatPending: "等待中",
    batchStatProcessing: "处理中",
    batchStatCompleted: "已完成",
    batchStatFailed: "失败",
    batchJobPending: "等待中",
    batchJobProcessing: "处理中",
    batchJobCompleted: "已完成",
    batchJobFailed: "失败",
    batchEmptyState: "队列为空。在上方添加股票代码以开始批量分析。",
    batchAutoRefreshHint: "每 15 秒自动刷新 · 切换标签页后仍保留队列列表",
    batchNoTickersError: "请输入至少一个股票代码",
    batchInvalidTickersError: "未找到有效的股票代码",
    batchColTicker: "代码",
    batchColCompany: "公司",
    batchColPrice: "股价",
    batchColConclusion: "结论",
    batchColStatus: "状态与进度",
    batchColActions: "操作",
    batchCreated: "创建时间",
    batchViewReport: "查看报告",
    batchLoadingReport: "加载中...",
    batchRetry: "重试",
    batchResume: "从中断点继续",
    batchRetrying: "重试中...",
    batchLoadReportError: "无法加载报告",
    batchEmptyReport: "报告数据为空",
    batchConclusionUnclassified: "未分类",
    batchConclusionStrongBuy: "强烈买入",
    batchConclusionBuy: "买入",
    batchConclusionStrongSell: "强烈卖出",
    batchConclusionSell: "卖出",
    batchConclusionHold: "持有",
    batchJobStatusTitle: "批量任务进行中",
    batchJobStatusSubtitle: "股票正在后台分析。可在此查看进度，或随时打开完整队列。",
    batchStatTotal: "总计",
    batchJobProgressLabel: "已完成 {done}/{total}",
    batchJobPollingHint: "正在自动更新 — 可离开此页，稍后在完整队列中查看。",
    batchJobViewQueue: "查看完整队列",
    batchJobCloseStatus: "关闭",
    reset: "开始新分析",
    findingCompanies: "正在识别相关公司...",
    analyzingCompany: "正在分析 {companyName}...",
    generatingQuestions: "正在生成研究问题...",
    answeringQuestions: "已完成 {current}/{total} 题...",
    synthesizingReport: "正在生成投资报告...",
    generatingFinalConclusion: "正在形成最终结论...",
    analysisComplete: "分析完成",
    focusAnalysisSaved: "核心公司分析完成，报告已保存。",
    savingFocusReport: "正在保存核心公司报告...",
    focusReportSaved: "核心公司报告已保存。可在各候选公司 Tab 中按需点击「开始分析」。",
    startCandidateAnalysis: "开始分析",
    startCandidateAnalysisHint: "详细分析（问题生成、问答、论点）仅在点击后运行，可节省 Token。",
    candidateAnalyzing: "正在分析候选公司...",
    stepTimelineToggle: "步骤耗时",
    stepTimelineTitle: "分析步骤耗时",
    focusCompany: "核心公司",
    candidateCompany: "候选公司",
    companyProfile: "公司简介",
    companyQuickTake: "公司速览",
    ticker: "股票代码",
    exchange: "交易所",
    currentPrice: "当前股价",
    dayChangePct: "日涨幅",
    high52w: "52周最高",
    low52w: "52周最低",
    profitLoss: "亏损",
    peTtm: "市盈率(PE)",
    marketCap: "总市值",
    floatMarketCap: "流通市值",
    weekChange: "周涨幅",
    monthChange: "月涨幅",
    investmentThesis: "投资论点",
    investmentNarrative: "投资叙事",
    crossDimensionalInsights: "跨维度洞察",
    finalConclusion: "最终投资结论",
    detailedAnalysis: "详细分析 (问答)",
    sources: "信息来源",
    followUp: "建议追问",
    askFollowUp: "提问选中项",
    errorTitle: "发生错误",
    interrupted: "分析已中断",
    interruptedMessage: "上次分析已中断。您可以查看已有进度或开始新的分析。",
    history: "历史记录",
    historyReportsTab: "分析报告",
    historyComparisonsTab: "对比历史",
    compareOpenResult: "打开对比结果",
    compareNewCompare: "新建对比",
    compareLoadingSessions: "加载对比历史...",
    compareSessionRunCount: "{count} 次对比",
    compareSidebarHint: "已保存的排名与得分，可随时重新打开。",
    compareHistoryInSidebar: "已保存的对比结果在左侧栏 →「对比历史」中查看。",
    clearHistory: "清空历史记录",
    loadReport: "加载报告",
    deleteReport: "删除报告",
    reportGeneratedAt: "报告生成时间",
    freshnessAuditTitle: "时效性审计",
    freshnessLatestPeriod: "检测到的最新周期",
    freshnessRecentCoverage: "最近三个月覆盖率",
    freshnessLatestQuarter: "是否包含最新已披露季度证据",
    freshnessLatestAnnual: "是否包含最新完整年报证据",
    freshnessFallbackCount: "回退到旧数据的回答数",
    emptyHistory: "暂无报告。完成一次分析后将在此处显示。",
    savingReport: "正在保存报告到历史记录...",
    progressReportSaved: "报告已更新，包含最新分析进度。",
    saveSuccess: "报告已成功保存到历史记录。",
    saveFailed: "报告未能保存到历史记录",
    followUpAnalysis: "跟进分析",
    followUpAll: "全部跟进",
    followUpCompany: "跟进此公司",
    followUpConfirmTitle: "开始跟进分析",
    followUpConfirmDesc: "将聚焦上次报告以来发生的变化。公司基础信息复用已有结论，调研重点放在期间事件与论点验证。",
    followUpPriorReport: "基准报告",
    followUpPriorConclusion: "上次结论",
    followUpPriorPrice: "上次股价",
    followUpCurrentPrice: "当前股价",
    followUpDaysSince: "距上次",
    followUpTargetCompanies: "跟进公司",
    followUpStart: "开始跟进",
    followUpCancel: "取消",
    followUpBannerTitle: "跟进分析",
    followUpVsPrior: "对比上次",
    followUpRatingUpgrade: "评级上调",
    followUpRatingMaintain: "评级维持",
    followUpRatingDowngrade: "评级下调",
    followUpPriceChange: "股价变化",
    followUpNoEligible: "没有可用于跟进的完整报告。",
    followUpLoadingPrices: "正在刷新行情...",
    followUpGeneratingQuestions: "正在生成跟进问题...",
    followUpViewPriorReport: "查看基准报告",
    viewInitialReport: "查看首次分析",
    compareVsPrevious: "相对上次",
    compareVsInitial: "相对首次",
    compareOpenReport: "打开完整报告 →",
    compareTitle: "跨公司横向对比",
    compareSubtitle: "从已保存报告中选择 2–5 家公司（focus 或 candidate），按胜率、盈利空间、错判保护、市场热点相关度排序。",
    compareBasketTab: "对比篮",
    compareHistoryTab: "对比历史",
    compareSelected: "已选公司",
    compareClearBasket: "清空对比篮",
    compareStart: "开始对比",
    compareRunning: "对比中…",
    comparePickFromHistory: "从历史报告选择公司",
    compareNoHistory: "暂无历史报告，请先完成一次分析。",
    compareNoEligible: "该报告中没有已完成分析的公司。",
    compareResultsTitle: "对比结果",
    compareRunAt: "对比时间",
    compareFollowUp: "跟进对比",
    compareFollowUpRefreshReports: "跟进对比（更新为最新报告）",
    compareChangeSummary: "相对上次对比的变化",
    compareHotTopics: "市场热点（D4）",
    compareHotTopicsAt: "热点检索时间",
    compareMatchedThemes: "匹配主题",
    comparePortfolioSummary: "组合结论",
    compareBackToBasket: "返回对比篮",
    compareNoSessions: "暂无已保存的对比。",
    compareSearchPlaceholder: "搜索公司名或股票代码…",
    compareSearchNoResults: "没有匹配的对比",
    compareUntitledSession: "未命名对比",
    compareViewLatest: "查看最新结果",
    viewCompare: "横向对比",
    compareSavedToDb: "已保存到数据库",
    compareSessionId: "会话 ID",
    compareRunId: "运行 ID",
    compareSavedHint: "可在「对比历史」中随时重新打开本次对比。",
    compareProgressTitle: "对比进行中",
    compareProgressSubtitle: "可留在本页或切换标签页，对比会在后台继续运行。",
    compareStepLoadingReports: "加载分析报告",
    compareStepBuildingDigests: "构建对比摘要",
    compareStepFetchingTopics: "检索市场热点",
    compareStepAiRanking: "AI 排序与打分",
    compareStepSaving: "保存对比结果",
    compareProgressHint: "5 家公司通常需要 1–3 分钟，AI 排序是最耗时的步骤。",
    compareProgressFailed: "对比失败",
    compareProgressPercent: "已完成 {percent}%",
    compareProgressCompanies: "本次对比公司",
    loginWithGoogle: "使用 Google 登录",
    loginSigningIn: "登录中...",
    loginTabSignIn: "登录",
    loginTabSignUp: "注册",
    loginEmailLabel: "邮箱",
    loginPasswordLabel: "密码",
    loginConfirmPasswordLabel: "确认密码",
    loginCodeLabel: "验证码",
    loginSendCode: "发送验证码",
    loginResendCode: "重新发送",
    loginResendIn: "{seconds} 秒后可重发",
    loginCompleteSignUp: "完成注册",
    loginSignInWithEmail: "邮箱登录",
    loginOrContinueWith: "或使用以下方式",
    loginCodeSentTo: "验证码已发送至 {email}",
    loginCodeDevHint: "未配置 SMTP，请在本地后端终端查看 6 位验证码。",
    loginPasswordHint: "至少 8 位",
    loginInvalidEmail: "请输入有效邮箱",
    loginNotConfigured: "未配置 Supabase 认证。Cloud Run 请设置 SUPABASE_URL 与 NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY（运行时生效）；本地开发请在 .env 中设置 VITE_SUPABASE_URL 与 VITE_SUPABASE_ANON_KEY。",
    usageTierFree: "免费：剩余 {remaining}/{limit} 次分析",
    usageTierLocked: "免费额度已用完 — 请订阅继续使用",
    usageTierPaid: "Pro：分析次数不限",
    usageFreeEnds: "免费窗口截止 {date}",
    usageRemaining: "剩余 {remaining}/{limit}",
    usageTrialEnds: "免费窗口截止 {date}",
    usageLimitReached: "请订阅后继续：首 7 天 $3.8 不限量，之后每月 $19.8。",
    upgrade: "订阅",
    memberProBadge: "Pro",
    subscriptionActiveTitle: "Pro 会员",
    subscriptionActiveSubtitle: "分析次数不限",
    subscriptionNextBilling: "预计下次扣款：{date}",
    subscriptionManageHint: "可在 PayPal 账户中管理或取消订阅",
    subscriptionTitle: "订阅 Pro 会员",
    subscriptionSubtitle: "首 7 天 $3.8，分析次数不限；7 天后 PayPal 每月自动扣费 $19.8。",
    subscriptionBenefits: [
      "每日公司分析次数不限",
      "首 7 天仅需 $3.8",
      "7 天后自动续费 $19.8/月（可在 PayPal 随时取消）",
      "报告云端保存、跨公司对比与收益追踪",
    ],
    subscriptionFootnote: "通过 PayPal 安全订阅，可随时在 PayPal 账户中取消。",
    signOut: "退出登录",
    returnTrackingTitle: "收益率跟踪（基准日买入）",
    returnTrackingHint: "假设在基准日按当时最新价买入；每次重新打开会记录一个时间点（同一天只保留最新一次）。",
    returnTrackingAnchorPrice: "基准价",
    returnTrackingCurrentPrice: "最新价",
    returnTrackingReturn: "累计涨跌",
    returnTrackingTimeline: "收益率时间轴",
    comparisonModeLabel: "对比基准",
    companyTimeline: "分析时间线",
    historyGroupedByTicker: "按公司",
    historyFlatList: "全部报告",
    timelineReports: "份报告",
    viewThisReport: "打开",
    currentReportMarker: "当前",
    compareBaselineDate: "基准日期",
    historyLoadError: "历史记录加载失败",
    historyRetry: "重试",
    historyReportCount: "已加载 {loaded} / {total} 份报告",
    historyLoadingMore: "正在加载更多报告…",
    historyEmptyAfterError: "报告可能仍在服务器上。请重试，或重启后端服务。",
    historySearchPlaceholder: "搜索公司名或股票代码…",
    historySearchNoResults: "没有匹配的报告",
    conclusion: {
      UpstreamSupplyChain: "上游/供应链",
      MarketPosition: "市场地位",
      BusinessModel: "商业模式",
      Financials: "财务状况",
      OutlookRisks: "前景与风险",
      MarketSentiment: "市场情绪",
      IndustryCycle: "行业周期",
      ExpectationGap: "市场预期差",
      summary: "总结",
      evidence: "证据"
    }
  }
};

export const getUIText = (lang: Language) => UI_TEXT[lang];
