
import { Language } from './types.ts';

export const UI_TEXT = {
  en: {
    title: "Intelligent Stock Agent",
    searchPlaceholder: "Enter company, ticker, or concept (e.g., 'Apple', 'AAPL', 'electric vehicles')",
    searchButton: "Analyze",
    languageToggle: "中文",
    reset: "New Analysis",
    findingCompanies: "Identifying relevant companies...",
    analyzingCompany: "Analyzing {companyName}...",
    generatingQuestions: "Generating research questions...",
    answeringQuestions: "Answering questions ({current}/{total})...",
    synthesizingReport: "Synthesizing investment thesis...",
    generatingFinalConclusion: "Formulating final conclusion...",
    analysisComplete: "Analysis Complete",
    focusCompany: "Focus Company",
    candidateCompany: "Candidate Company",
    companyProfile: "Company Profile",
    ticker: "Ticker",
    exchange: "Exchange",
    currentPrice: "Current Price",
    weekChange: "1-Week Change",
    monthChange: "1-Month Change",
    investmentThesis: "Investment Thesis",
    finalConclusion: "Final Investment Conclusion",
    detailedAnalysis: "Detailed Analysis (Q&A)",
    sources: "Sources",
    followUp: "Suggested Follow-up Questions",
    askFollowUp: "Ask Selected",
    errorTitle: "An Error Occurred",
    interrupted: "Analysis Interrupted",
    interruptedMessage: "The previous analysis was interrupted. You can review the progress made or start a new analysis.",
    history: "History",
    clearHistory: "Clear All History",
    loadReport: "Load Report",
    deleteReport: "Delete Report",
    emptyHistory: "No reports found. Complete an analysis to see it here.",
    conclusion: {
      UpstreamSupplyChain: "Upstream/Supply Chain",
      MarketPosition: "Market Position",
      BusinessModel: "Business Model",
      Financials: "Financials",
      OutlookRisks: "Outlook & Risks",
      summary: "Summary",
      evidence: "Evidence"
    }
  },
  cn: {
    title: "智能股票投研助手",
    searchPlaceholder: "输入公司、代码或概念（如 '苹果', 'AAPL', '新能源汽车'）",
    searchButton: "开始分析",
    languageToggle: "English",
    reset: "开始新分析",
    findingCompanies: "正在识别相关公司...",
    analyzingCompany: "正在分析 {companyName}...",
    generatingQuestions: "正在生成研究问题...",
    answeringQuestions: "正在回答问题 ({current}/{total})...",
    synthesizingReport: "正在生成投资报告...",
    generatingFinalConclusion: "正在形成最终结论...",
    analysisComplete: "分析完成",
    focusCompany: "核心公司",
    candidateCompany: "候选公司",
    companyProfile: "公司简介",
    ticker: "股票代码",
    exchange: "交易所",
    currentPrice: "当前股价",
    weekChange: "周涨幅",
    monthChange: "月涨幅",
    investmentThesis: "投资论点",
    finalConclusion: "最终投资结论",
    detailedAnalysis: "详细分析 (问答)",
    sources: "信息来源",
    followUp: "建议追问",
    askFollowUp: "提问选中项",
    errorTitle: "发生错误",
    interrupted: "分析已中断",
    interruptedMessage: "上次分析已中断。您可以查看已有进度或开始新的分析。",
    history: "历史记录",
    clearHistory: "清空历史记录",
    loadReport: "加载报告",
    deleteReport: "删除报告",
    emptyHistory: "暂无报告。完成一次分析后将在此处显示。",
    conclusion: {
      UpstreamSupplyChain: "上游/供应链",
      MarketPosition: "市场地位",
      BusinessModel: "商业模式",
      Financials: "财务状况",
      OutlookRisks: "前景与风险",
      summary: "总结",
      evidence: "证据"
    }
  }
};

export const getUIText = (lang: Language) => UI_TEXT[lang];
